# Generated by Django 5.1.3 on 2024-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
